kind: pipeline
name: drone-portainer-deploy
type: docker

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_hub_username
    auth:
      from_secret: docker_hub_password
    repo: lmilius-homelab/drone-portainer-deploy
    auto_tag: true